version: "3.9"
services:
  bot:
    environment:
      - CONFIG_PATH=/run/secrets/bot_config
      - SERVER_HOST=http://server:3001 
    secrets:
      - bot_config
    links: 
      - "server"

  server:
    ports:
      - "3001:3001"
    environment:
      - CONFIG_PATH=/run/secrets/server_config
    secrets:
      - server_config

# https://serverfault.com/a/936262
secrets:
  bot_config:
    file: ./bot-config.yml  
  server_config:
    file: ./server-config.yml