name: "Update Docker Image in Production"
description: "Updates the Docker Image in my Digital Ocean Server"
inputs:
  service:
    required: true
    description: "The name of the service to update"
  # Remember that Composite actions cannot read secrets.
  ssh_host:
    required: true
    description: "The host IP of the Digital Ocean server"
  ssh_key:
    required: true
    description: "The SSH key to use for authentication"

# https://phoenixnap.com/kb/update-docker-image-container
runs:
  using: "composite"
  steps:
    - name: Download and extract the latest Docker Image on Server
      uses: appleboy/ssh-action@1a8b3784eaa665f677fa114edd5683bb6a6bfaa8
      with:
        host: ${{ inputs.ssh_host }}
        username: joshua
        key: ${{ inputs.ssh_key }}
        port: 22
        # https://stackoverflow.com/a/56687449
        script: |
          cd ~/projects/treehouse-bot
          docker container ls | grep treehouse
          docker image ls | grep treehouse
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
          docker image prune -f
          docker container prune -f
