name: "Build and Scan Docker Image"
description: "Build and Scan a Docker Image"
inputs:
  service:
    required: true
    description: "The name of the service to build and scan"

runs:
  using: "composite"
  steps:
    - name: Build the Docker Image
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.dev.yml build ${{ inputs.service }}
      shell: bash

    - name: Run `docker image ls`
      run: |
        docker image ls
      shell: bash

    - name: Scan Docker image
      uses: azure/container-scan@595707a78db6069af4db7d81902d7a886ec73973
      with:
        image-name: treehouse-bot_${{ inputs.service }}
