name: 'Build Docker Image with Caching'
description: 'DOCKER BUILDX IS GREAT'
inputs:
  service:
    required: true
    description: 'The name of the service to build and deploy (bot or server)'
  outputs:
    required: false
    description: Same as docker-push-action outputs. Set this if you want to store the docker iamge as an artifact.
  tags:
    required: true
    description: 'tags to add to the image'

runs:
  using: composite
  steps:
    - name: 🐳 Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1.6.0
      with:
        install: true

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@4
      with:
        images: ghcr.io/${{ github.repository }}

    - name: 🏗️ Build Image
      uses: docker/build-push-action@v4
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: apps/${{ inputs.service }}/Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ inputs.tags }}
        load: true
        outputs: ${{ inputs.outputs }} # for us to store docker images as artifacts. If not set, we will not store the image

    - name: List Docker Images
      run: docker images
      shell: bash
