name: "Build and Deploy Docker Image"
description: "Build and deploy a Docker image to GitHub Container Registry"
inputs:
  service:
    required: true
    description: "The name of the service to build and deploy"
  repo_token:
    required: true
    description: "The GitHub token to use for authentication"

runs:
  using: "composite"
  steps:
    - name: Login to Github Container Registry
      uses: docker/login-action@219c305e1ce92a755f3aa4ba17387c95df31e987
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.repo_token }}

    - name: Build the Docker Image
      uses: ./.github/actions/build-docker-image-cache
      with:
        service: ${{ inputs.service }}
        repo_token: ${{ inputs.repo_token }}
        tags: ${{ env.TAG_PREFIX }}:${{ github.sha }},${{ env.TAG_PREFIX }}:latest
      env:
        TAG_PREFIX: "ghcr.io/${{ github.repository }}.${{ inputs.service }}"

    - name: Run `docker images`
      run: docker images
      shell: bash

    # Note: global environment variables don't seem possible right now...
    # https://github.com/actions/starter-workflows/issues/68

    - name: Push Docker Image with SHA and :latest tag
      run: |
        docker push ${{ env.TAG_PREFIX }}:latest
        docker push ${{ env.TAG_PREFIX }}:${{ github.sha }}
      shell: bash
      env:
        TAG_PREFIX: "ghcr.io/${{ github.repository }}.${{ inputs.service }}"
