name: "Build and Deploy Docker Image"
description: "Build and deploy a Docker image to GitHub Container Registry"
inputs:
  service:
    required: true
    description: "The name of the service to build and deploy"
  repo_token:
    required: true
    description: "The GitHub token to use for authentication"

runs:
  using: "composite"
  steps:
    - name: Login to Github Container Registry
      uses: docker/login-action@17f28ab24d0d2832d5ff23a1409bbfc373ebcb96
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.repo_token }}

    - name: Build the Docker Image
      uses: ./.github/actions/build-docker-image-cache
      with:
        service: ${{ inputs.service }}
        repo_token: ${{ inputs.repo_token }}
        output_prefix: treehouse-bot
        tags: ${{ github.repository }}_${{ inputs.service }}

    - name: Run `docker images`
      run: docker images
      shell: bash

    # Note: global environment variables don't seem possible right now...
    # https://github.com/actions/starter-workflows/issues/68

    - name: Push Docker Image with SHA Tag
      run: |
        docker tag treehouse-bot_${{ inputs.service }} $TAG_PREFIX:${{ github.sha }}
        docker push $TAG_PREFIX:${{ github.sha }}
      shell: bash
      env:
        TAG_PREFIX: "ghcr.io/${{ github.repository }}.${{ inputs.service }}"

    - name: Push Docker Image with :latest tag
      run: |
        docker tag treehouse-bot_${{ inputs.service }} $TAG_PREFIX:latest
        docker push $TAG_PREFIX:latest
      shell: bash
      env:
        TAG_PREFIX: "ghcr.io/${{ github.repository }}.${{ inputs.service }}"
