name: "Build and Deploy Docker Image"
description: "Build and deploy a Docker image to GitHub Container Registry"
inputs:
  service:
    required: true
    description: "The name of the service to build and deploy"
  repo_token:
    required: true
    description: "The GitHub token to use for authentication"

runs:
  using: "composite"
  steps:
    - name: Login to Github Container Registry
      uses: docker/login-action@5fcefb941de79536616e9422226e33fd39f1706f
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.repo_token }}

    - name: Build the Docker Image
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.dev.yml build ${{ inputs.service }}
      shell: bash

    - name: Run `docker image ls`
      run: |
        docker image ls
      shell: bash

    - name: Scan Docker image
      uses: azure/container-scan@595707a78db6069af4db7d81902d7a886ec73973
      with:
        image-name: treehouse-bot_${{ inputs.service }}

    # Note: global environment variables don't seem possible right now...
    # https://github.com/actions/starter-workflows/issues/68

    - name: Push Docker Image with SHA Tag
      run: |
        docker tag treehouse-bot_${{ inputs.service }} $TAG_PREFIX:${{ github.sha }}
        docker push $TAG_PREFIX:${{ github.sha }}
      shell: bash
      env:
        TAG_PREFIX: "ghcr.io/${{ github.repository }}.${{ inputs.service }}"

    - name: Push Docker Image with :latest tag
      run: |
        docker tag treehouse-bot_${{ inputs.service }} $TAG_PREFIX:latest
        docker push $TAG_PREFIX:latest
      shell: bash
      env:
        TAG_PREFIX: "ghcr.io/${{ github.repository }}.${{ inputs.service }}"
