name: Testing Supabase

on:
  push:
    branches:
      - nft-cmd

jobs:
  stuff:
    name: Installs and runs supabase
    runs-on: ubuntu-latest # for easier install of supabase
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: See if Homebrew is installed
        run: brew --version

      - name: Install Supabase
        run: |
          brew install supabase/tap/supabase
          supabase --version

      # https://github.com/supabase/cli/tree/main/examples/tour
      - name: Connect remote DB
        run: |
          supabase db remote set 'postgresql://postgres:${{ secrets.SUPABASE_POSTGRES_PWD }}@db.${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co:5432/postgres'
          supabase db remote commit

      - name: Check contents
        run: |
          ls -al
          cd supabase/migrations
          ls -al
          cd ../..

      - name: Run Supabase Start
        run: supabase start
